### PR TITLE
MOD-1956

### PR DESCRIPTION
**Pull request by manojdcoder**
Increased the scanning area size

### CODE REVIEW

**Comment by m1ga** [comment]
could you make this as a parameter, so you can set it on creation? On a Samsung S6 this area could be bigger

**Comment by hansemannn** [comment]
@m1ga I want to remove some dust from this module, could you help here? Or we could even update the whole ZXing library to latest :-)

**Comment by m1ga** [comment]
@hansemannn perhaps :-D https://github.com/appcelerator-archive/ti.barcode/pull/46

**Comment by hansemannn** [comment]
Closing as part of #46 .

**Pull request closed without merging**
